# Generated by Django 5.1.4 on 2025-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_awarts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('agress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('photo', models.BigIntegerField(verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterModelOptions(
            name='awarts',
            options={'verbose_name': 'О нас (галерея)', 'verbose_name_plural': 'О нас (галерея)'},
        ),
    ]
