# Generated by Django 5.1.4 on 2025-01-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_agress_contact_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='over',
            name='date',
        ),
    ]
