# Generated by Django 5.1.4 on 2025-01-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image_title_delete_awarts_delete_contact_delete_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video', models.URLField(verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Настройка (about)',
                'verbose_name_plural': 'Настройки (about)',
            },
        ),
        migrations.CreateModel(
            name='Awarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='awarts/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото (about)',
                'verbose_name_plural': 'Фотки (about)',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.BigIntegerField(verbose_name='Номер телефона')),
                ('title_2', models.CharField(max_length=255, verbose_name='Нижний загаловок')),
                ('description_2', models.TextField(verbose_name='Описание нижнего загаловка')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('banner', models.ImageField(upload_to='banner/', verbose_name='Фото баннера')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Настройка главной',
                'verbose_name_plural': 'Настройки главной',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
