# Generated by Django 5.1.4 on 2025-01-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_about_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.FileField(upload_to='video/', verbose_name='Видео'),
        ),
    ]
