# Generated by Django 5.1.4 on 2025-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_about_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=255, verbose_name='Награда')),
                ('achievement', models.TextField(verbose_name='Достижение')),
                ('number_awards', models.TextField(verbose_name='Количесто наград')),
            ],
            options={
                'verbose_name': 'Настройка (about)',
                'verbose_name_plural': 'Настройки (about)',
            },
        ),
    ]
