# Generated by Django 5.1.4 on 2025-01-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_list_awards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_awards',
            options={'verbose_name': 'Награда (about)', 'verbose_name_plural': 'Награды (about)'},
        ),
    ]
