# Generated by Django 5.1.4 on 2025-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_list_awards_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=255, verbose_name='Направление')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Направление (about)',
                'verbose_name_plural': 'Направления (about)',
            },
        ),
        migrations.DeleteModel(
            name='List_Awards',
        ),
    ]
