# Generated by Django 5.1.4 on 2025-01-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_list_directions_delete_list_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя отпровителя')),
                ('email', models.EmailField(max_length=254, verbose_name='email отпровителя')),
                ('message', models.TextField(verbose_name='Сщщбщение')),
            ],
            options={
                'verbose_name': 'Оставленный отзыв',
                'verbose_name_plural': 'Оставленные отзывы',
            },
        ),
        migrations.DeleteModel(
            name='List_Directions',
        ),
    ]
