# Generated by Django 5.1.4 on 2025-01-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_form_delete_list_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=100, verbose_name='ID пользовотеля')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('chat_id', models.CharField(max_length=100, verbose_name='Чат ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь телегрм',
                'verbose_name_plural': 'Пользователи телегрма',
            },
        ),
    ]
